### ISSUE TITLE
there is no model-00001-of-00002.safetensors,model-00002-of-00002.safetensors in Llama-2-7b-chat-hf-qformer 

### ISSUE THREAD

**Issue by bocaidoufuyushiren** [Sreyan88/GAMA#1]

**Comment by Sreyan88** [comment]
Hello, We are still in the process of adding details to the readme. However, to answer your question, you need to download the `model-00001-of-00002.safetensors` and `model-00002-of-00002.safetensors` from the official repo here: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

Unfortunately, the Llama license does not allow redistribution, so we cannot directly share it with you.

**Comment by Sreyan88** [comment]
Update: We will be uploading `model-00001-of-00002.safetensors` and `model-00002-of-00002.safetensors` soon (in a few hours)

**Comment by bocaidoufuyushiren** [comment]
thank you
