### ISSUE TITLE
Inference on a single audio input

### ISSUE THREAD

**Issue by jrohsc** [Sreyan88/GAMA#18]
Hi, 

I tried to modify the`gama_inf.py` code to test the model on a single audio input. However, I am encountering some issues with the following: `ValueError: The following "model_kwargs" are not used by the model: ['audio_input'] (note: typos in the generate arguments will also show up in this list)`. 

Is there a way to fix this error? Or do you guys possess any code that we can test the model on a single audio input?

**Comment by sonalkum** [comment]
Can you share your gama_inf.py file so that we can try to reproduce this issue? We have never encountered this issue. You can also check https://huggingface.co/spaces/sonalkum/GAMA here for better clarity on how to infer on single audio.

**Comment by jrohsc** [comment]
Is there a way to do it on a code instead of a demo? A notebook file would be helpful!

**Comment by Sreyan88** [comment]
Hi @jrohsc ,

I am thinking you might have missed installing our version of Transformers. Please check installation instructions here:

https://github.com/Sreyan88/GAMA?tab=readme-ov-file#setup-%EF%B8%8F

**Comment by jrohsc** [comment]
Here is my ipynb code I used on my local machine. Assume that this is in the GAMA directory. https://drive.google.com/file/d/1biav6H9EEvDzPG4GSt1CdSPvnUIJs00V/view?usp=sharing

**Comment by jrohsc** [comment]
Hi, I even used the python script but I got the same error even I installed based on the instruction. I downloaded the `Llama-2-7b-chat-hf-qformer` folder as the base model and used the `checkpoint-2500/pytorch_model.bin` as the eval model path. What could be the potential reason for the above error?

**Comment by sonalkum** [comment]
Hi @jrohsc, I've added the code to infer on single audio. Please find the code [here](https://github.com/Sreyan88/GAMA/blob/main/gama_inf_single_audio.py).

**Comment by jrohsc** [comment]
Hi, thank you very much for uploading the file. However, i don't know why but I'm getting the same error saying `ValueError: The following "model_kwargs" are not used by the model: ['audio_input'] (note: typos in the generate arguments will also show up in this list)`

**Comment by sonalkum** [comment]
Hi @jrohsc , how are you installing transformers and peft?

**Comment by jrohsc** [comment]
I used `pip install -r requirements.txt` to install all of them.

**Comment by sonalkum** [comment]
Please use the following command to install transformers and peft as we have already mentioned in readme:

```
pip install -e hf-dev-train/transformers-main
pip install -e peft-main
```

Also, in your inference notebook I see that you are not setting base_model path to "Llama-2-7b-chat-hf-qformer". Please make sure to download it and set base_model path to this.

**Comment by jrohsc** [comment]
Also for the `torchaudio`, which version does it have to be?

**Comment by sonalkum** [comment]
Please refer requirements.txt.

**Comment by jrohsc** [comment]
Seems like it is working now. Thanks! 
Is the model also capable of SQA tasks? If so, how should I provide the instruction?

**Comment by sonalkum** [comment]
If you mean Speech QA, then no, GAMA currently doesn't support Speech Question Answering. Please let me know if you mean something else by SQA.
