### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by asigalov61** [Sreyan88/GAMA#19]
@sonalkum @Sreyan88 Hello,

I just wanted to thank you for this model! It's very nice and I think I will be able to put it to good use for my research and projects :)

I have a few questions though...

1) What is the difference between GAMA and GAMAIT? Can you elaborate in detail as it was not very clear to me?

2) What is the maximum length of audio that can be analyzed? 10sec?

3) Can you provide a streamlined inference demo colab notebook so that its easier to setup and run?

Thank you very much.

Sincerely,

Alex

**Comment by sonalkum** [comment]
Hi @asigalov61, thank you for your appreciation.

1. GAMA-IT is GAMA instruction tuned on CompA-R dataset.
2. Yes, maximum length of audio that can be analyzed is 10 seconds.
3. You can use https://github.com/Sreyan88/GAMA/blob/main/gama_inf_single_audio.py for inferring on single audio and can use this code with notebooks as well.

**Comment by asigalov61** [comment]
@sonalkum Thank you very much for your responses :)
