### ISSUE TITLE
About the music dataset in OpenAQA dataset.

### ISSUE THREAD

**Issue by blue-blue272** [Sreyan88/GAMA#2]
This paper augmented openAQA with 4 music datasets: MusicCap, MusicQA, Nsynth and Magna. Can you release the related question-answer pairs?

**Comment by Sreyan88** [comment]
Thank You for the question! We will upload our entire OpenAQA dataset in a few hours!

**Comment by Sreyan88** [comment]
We have upload the dataset on our common drive! The dataset is named openaqa_gama.json

Thank You and feel free to reopen if you find any difficulty!

**Comment by blue-blue272** [comment]
> We have upload the dataset on our common drive! The dataset is named openaqa_gama.json
> 
> Thank You and feel free to reopen if you find any difficulty!

Thanks a lot. Where can I find the openaqa_gamma.json?

**Comment by Sreyan88** [comment]
Here:

https://drive.google.com/file/d/1UL7sRSkqlmk9H2NuANoCqAkd9ixS-vbn/view?usp=drive_link
