### ISSUE TITLE
Unused ['audio_input'] Argument in model_kwargs Causing ValueError

### ISSUE THREAD

**Issue by Hannieliao** [Sreyan88/GAMA#4]
Hi! Thanks for your amazing work!
I am trying the inference: python gama_inf.py with:
"checkpoint-2500/pytorch_model.bin"

However, I face the following error：
ValueError: The following `model_kwargs` are not used by the model: ['audio_input'] (note: typos in the generate arguments will also show up in this list)

Could you please give some help~

**Comment by Sreyan88** [comment]
Thank You for using GAMA! Just confirming if you have installed our version of `transformers` ?

The steps are here:

https://github.com/Sreyan88/GAMA?tab=readme-ov-file#setup-%EF%B8%8F

Once you confirm we can look more into this!

**Comment by Hannieliao** [comment]
Thank you so much! 
Took your advice, the issue is solved.
Thanks！

**Comment by Sreyan88** [comment]
Thank You! Feel free to re-open if you need any more help!
