### ISSUE TITLE
missing state dict

### ISSUE THREAD

**Issue by haidog-yaqub** [Sreyan88/GAMA#5]
thank you so much for the amazing work.

i found some state dicts are missing in the uploaded checkpoint safetensors, would this influence model performance?

model.audio_encoder.norm_j.weight
model.audio_encoder.norm_j.bias
model.audio_encoder.norm_k.weight
model.audio_encoder.norm_k.bias
model.audio_proj_qformer.0.weight
model.audio_proj_qformer.0.bias
model.audio_proj_qformer.2.weight
model.audio_proj_qformer.2.bias
model.audio_proj_audioenc.0.weight
model.audio_proj_audioenc.0.bias
model.audio_proj_audioenc.2.weight
model.audio_proj_audioenc.2.bias
model.audio_aggregator_layer_1.attention.self.query.weight
model.audio_aggregator_layer_1.attention.self.query.bias
model.audio_aggregator_layer_1.attention.self.key.weight
model.audio_aggregator_layer_1.attention.self.key.bias
model.audio_aggregator_layer_1.attention.self.value.weight
model.audio_aggregator_layer_1.attention.self.value.bias
model.audio_aggregator_layer_1.attention.output.dense.weight
model.audio_aggregator_layer_1.attention.output.dense.bias
model.audio_aggregator_layer_1.attention.output.LayerNorm.weight
model.audio_aggregator_layer_1.attention.output.LayerNorm.bias
model.audio_aggregator_layer_1.crossattention.self.query.weight
model.audio_aggregator_layer_1.crossattention.self.query.bias
model.audio_aggregator_layer_1.crossattention.self.key.weight
model.audio_aggregator_layer_1.crossattention.self.key.bias
model.audio_aggregator_layer_1.crossattention.self.value.weight
model.audio_aggregator_layer_1.crossattention.self.value.bias
model.audio_aggregator_layer_1.crossattention.output.dense.weight
model.audio_aggregator_layer_1.crossattention.output.dense.bias
model.audio_aggregator_layer_1.crossattention.output.LayerNorm.weight
model.audio_aggregator_layer_1.crossattention.output.LayerNorm.bias
model.audio_aggregator_layer_1.intermediate.dense.weight
model.audio_aggregator_layer_1.intermediate.dense.bias
model.audio_aggregator_layer_1.output.dense.weight
model.audio_aggregator_layer_1.output.dense.bias
model.audio_aggregator_layer_1.output.LayerNorm.weight
model.audio_aggregator_layer_1.output.LayerNorm.bias
model.audio_aggregator_layer_1.intermediate_query.dense.weight
model.audio_aggregator_layer_1.intermediate_query.dense.bias
model.audio_aggregator_layer_1.output_query.dense.weight
model.audio_aggregator_layer_1.output_query.dense.bias
model.audio_aggregator_layer_1.output_query.LayerNorm.weight
model.audio_aggregator_layer_1.output_query.LayerNorm.bias
model.audio_aggregator_layer_2.attention.self.query.weight
model.audio_aggregator_layer_2.attention.self.query.bias
model.audio_aggregator_layer_2.attention.self.key.weight
model.audio_aggregator_layer_2.attention.self.key.bias
model.audio_aggregator_layer_2.attention.self.value.weight
model.audio_aggregator_layer_2.attention.self.value.bias
model.audio_aggregator_layer_2.attention.output.dense.weight
model.audio_aggregator_layer_2.attention.output.dense.bias
model.audio_aggregator_layer_2.attention.output.LayerNorm.weight
model.audio_aggregator_layer_2.attention.output.LayerNorm.bias
model.audio_aggregator_layer_2.crossattention.self.query.weight
model.audio_aggregator_layer_2.crossattention.self.query.bias
model.audio_aggregator_layer_2.crossattention.self.key.weight
model.audio_aggregator_layer_2.crossattention.self.key.bias
model.audio_aggregator_layer_2.crossattention.self.value.weight
model.audio_aggregator_layer_2.crossattention.self.value.bias
model.audio_aggregator_layer_2.crossattention.output.dense.weight
model.audio_aggregator_layer_2.crossattention.output.dense.bias
model.audio_aggregator_layer_2.crossattention.output.LayerNorm.weight
model.audio_aggregator_layer_2.crossattention.output.LayerNorm.bias
model.audio_aggregator_layer_2.intermediate.dense.weight
model.audio_aggregator_layer_2.intermediate.dense.bias
model.audio_aggregator_layer_2.output.dense.weight
model.audio_aggregator_layer_2.output.dense.bias
model.audio_aggregator_layer_2.output.LayerNorm.weight
model.audio_aggregator_layer_2.output.LayerNorm.bias
model.audio_aggregator_layer_2.intermediate_query.dense.weight
model.audio_aggregator_layer_2.intermediate_query.dense.bias
model.audio_aggregator_layer_2.output_query.dense.weight
model.audio_aggregator_layer_2.output_query.dense.bias
model.audio_aggregator_layer_2.output_query.LayerNorm.weight
model.audio_aggregator_layer_2.output_query.LayerNorm.bias

**Comment by Sreyan88** [comment]
Hello! Thank You for the issue!

We do checkpoint loading in 2 parts:

1) The first part loads all pre-trained parts of GAMA. This is done through safetensors in [this line](https://github.com/Sreyan88/GAMA/blob/main/gama_inf.py#L201).

2) Audio aggregator layers and feature projection layers are not pre-trained and trained by us. Thus, [this line](https://github.com/Sreyan88/GAMA/blob/main/gama_inf.py#L216-L218) loads it from our provided checkpoint.

Thank You!

**Comment by haidog-yaqub** [comment]
> Hello! Thank You for the issue!
> 
> We do checkpoint loading in 2 parts:
> 
> 1. The first part loads all pre-trained parts of GAMA. This is done through safetensors in [this line](https://github.com/Sreyan88/GAMA/blob/main/gama_inf.py#L201).
> 2. Audio aggregator layers and feature projection layers are not pre-trained and trained by us. Thus, [this line](https://github.com/Sreyan88/GAMA/blob/main/gama_inf.py#L216-L218) loads it from our provided checkpoint.
> 
> Thank You!

I got it. thank you so much!
