### ISSUE TITLE
error processing the audio files

### ISSUE THREAD

**Issue by deek2689** [Sreyan88/GAMA#6]
Trying to run emotion recognition task using IEMOCAP dataset (audio samples)
When running gama_inf.py got this error.
ValueError: The following model_kwargs are not used by the model: ['audio_input'] (note: typos in the generate arguments will also show up in this list)

1. Used IEMOCAP dataset wav files for processing
2. used the given CLAP checkpoints

**Comment by Sreyan88** [comment]
Hello, We suspect you might not have installed our version of hf. Please see instructions to install [here](https://github.com/Sreyan88/GAMA?tab=readme-ov-file#setup-%EF%B8%8F).

`pip install -e hf-dev-train/transformers-main`

**Comment by deek2689** [comment]
Thanks that worked. I missed the setup.
