### ISSUE TITLE
Weird bug during the inference.

### ISSUE THREAD

**Issue by dragonlzm** [Sreyan88/GAMA#8]
I tried to run the Inference of GAMA on CompA-R benchmark following the instruction in Readme: 
Here is what I did before I meet the bug:
1. I follow the insturction on the Readme to install the environment, which succeed.
2. I download the 'Llama-2-7b-chat-hf-qformer.zip' from google drive and unzip it. Then I change the line 189 `base_model: str = "/fs/nexus-projects/brain_project/Llama-2-7b-chat-hf-qformer",` in gama_inf.py to the folder where Llama-2-7b-chat-hf-qformer is
3. I download 'stage5_epoch2.zip' from google drive, and change the line 216 in gama_inf.py `eval_mdl_path = '/fs/gamma-projects/audio/gama/new_data/stage5/checkpoint-2500/pytorch_model.bin'` accordingly.
4. Finally I download the 'compar-test-audios.tar.gz' and 'CompA-R.json' and change the path in gama_inf.py accordingly. 

When I run the python gama_inf.py, I saw following bug, do you have any idea what cause the bug? Thanks!
![image](https://github.com/user-attachments/assets/c8d8253c-05af-403a-8ff4-6d5ed309bb18)

**Comment by dragonlzm** [comment]
Also when I try to unzip the Llama-2-7b-chat-hf-qformer.zip, I notice another error 'error: invalid zip file with overlapped components (possible zip bomb)'. Should I unzip it anyway?
![image](https://github.com/user-attachments/assets/c3142465-f4e9-4780-a9f5-10ac37807c81)

**Comment by Sreyan88** [comment]
For the 1st issue, please refer to Issue #3 . It might be the GPU you are trying to infer the model on. For the second, let me try to check on my end once.

**Comment by dragonlzm** [comment]
Thanks for the response. I am actually able to run the `inference_gradio_gama.py` smoothly with the same machine and with minor modification. So the checkpoint unzip issue should be fine. Thanks anyway!

**Comment by dragonlzm** [comment]
I notice that this the first bug is caused by using one GPU for inference. If I run the inference on 2 gpus machine then the bug will disappear.  Do you have any thought how could I inference on one gpu? And why this is the case? Thanks!

**Comment by sonalkum** [comment]
Hi @dragonlzm, we have not noticed any such bug while running the inference on 1 GPU. Can you tell us which GPU are you using?
