### ISSUE TITLE
Additional checkpoint

### ISSUE THREAD

**Issue by dragonlzm** [Sreyan88/GAMA#9]
Hi! I notice that in your demo script, you use a checkpoint which is `/fs/gamma-projects/audio/gama/new_data/stage4_all_mix_new/checkpoint-46800/pytorch_model.bin` Does this checkpoint provide better performance? Could you please also release this checkpoint? Thanks!

**Comment by Sreyan88** [comment]
@sonalkum do you have an answer to this please? Thank You!

**Comment by sonalkum** [comment]
Hi @dragonlzm, no we don't have any additional checkpoints. The comments are from additional experiments. Kindly ignore that. The best checkpoints are released.
